manifest:
  remotes:
    - name: theol0403
      url-base: https://github.com/theol0403
  projects:
    - name: zmk
      remote: theol0403
      revision: main
      import: app/west.yml
  self:
    path: config
